import test from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync,writeFileSync,mkdirSync,readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { LearningService } from "../lib/learning-service.js";
import { transaction,digest } from "../lib/local-store.js";
import { createLocalServer } from "../local-service.js";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StdioClientTransport } from "@modelcontextprotocol/sdk/client/stdio.js";
import { fileURLToPath } from "node:url";
import { performance } from "node:perf_hooks";
import { spawn } from "node:child_process";

const root=()=>mkdtempSync(join(tmpdir(),"gongkao-test-"));
const question=(i,extra={})=>({question_id:`fixture_${i}`,question_type:"SINGLE",interactive_supported:true,source_type:"practice",exam_type:"省考",module:"资料分析",subtype:"增长率",stem:`验证题 ${i}`,options:[{label:"A",text:"正确选项"},{label:"B",text:"错误选项"}],correct_answer:"A",paper_id:"fixture_paper",paper_position:i+1,paper_total:20,...extra});
function fixture(options={}){const dir=root();const bankPath=join(dir,"questions.jsonl");writeFileSync(bankPath,Array.from({length:20},(_,i)=>JSON.stringify(question(i))).join("\n"));const service=new LearningService({root:join(dir,"data"),bankPath,...options});const binding=service.initialize({name:"测试学习者",idempotency_key:"init"}).binding_id;return {dir,bankPath,service,binding};}
function answer(service,binding,view,value="A",key=crypto.randomUUID()){return service.submit(binding,{session_id:view.session_id,question_id:view.payload.question.question_id,session_item_id:view.payload.session_item_id,answer:value,idempotency_key:key});}
const next=(s,b,v)=>s.next(b,{session_id:v.session_id,idempotency_key:crypto.randomUUID()});

test("review stages follow 1/3/7/14/30-day intervals and a wrong review moves back",()=>{let clock=new Date("2026-01-01T00:00:00Z");const f=fixture({now:()=>clock});try{let v=f.service.start(f.binding,{count:1,idempotency_key:"s"});answer(f.service,f.binding,v,"B");let task=f.service.learningContext(f.binding).state.review_queue[0];assert.equal(new Date(task.due_at)-clock,86400000);for(const days of [3,7,14,30]){clock=new Date(task.due_at);v=f.service.start(f.binding,{session_mode:"review",count:1,ignore_unfinished:true,idempotency_key:crypto.randomUUID()});answer(f.service,f.binding,v);task=f.service.learningContext(f.binding).state.review_queue[0];assert.equal(new Date(task.due_at)-clock,days*86400000);}clock=new Date(task.due_at);v=f.service.start(f.binding,{session_mode:"review",count:1,ignore_unfinished:true,idempotency_key:"fail-review"});answer(f.service,f.binding,v,"B");task=f.service.learningContext(f.binding).state.review_queue[0];assert.equal(task.stage,3);assert.equal(new Date(task.due_at)-clock,14*86400000);}finally{f.service.close();}});
test("foundation refuses mixed concepts and module-level tags",()=>{const f=fixture();try{assert.throws(()=>f.service.start(f.binding,{purpose:"foundation",focus_module:"资料分析",focus_subtype:"资料分析",idempotency_key:"broad"}),{code:"INVALID_INPUT"});assert.throws(()=>f.service.start(f.binding,{purpose:"foundation",focus_module:"资料分析",focus_subtype:"增长率",questions:Array.from({length:15},(_,i)=>question(i,{subtype:i===14?"比重":"增长率"})),idempotency_key:"mixed"}),{code:"INVALID_INPUT"});assert.throws(()=>f.service.start(f.binding,{purpose:"foundation",focus_module:"资料分析",focus_subtype:"增长率",questions:Array.from({length:14},(_,i)=>question(i)),idempotency_key:"short"}),{code:"INVALID_INPUT"});assert.throws(()=>f.service.start(f.binding,{purpose:"foundation",focus_module:"数量关系",focus_subtype:"增长率",questions:Array.from({length:15},(_,i)=>question(i)),idempotency_key:"wrong-module"}),{code:"INVALID_INPUT"});assert.equal(f.service.report(f.binding).total_attempts,0);}finally{f.service.close();}});

test("process termination during a SQLite write rolls back attempts and the profile together",{timeout:10000},async()=>{
  const f=fixture();const v=f.service.start(f.binding,{count:1,idempotency_key:"s"});
  const worker=fileURLToPath(new URL("./fixtures/crash-writer.js",import.meta.url));
  const child=spawn(process.execPath,[worker,join(f.dir,"data"),f.binding,v.session_id],{stdio:["ignore","ignore","ignore","ipc"],windowsHide:true});
  try{
    await new Promise((resolve,reject)=>{child.once("message",resolve);child.once("error",reject);child.once("exit",(code)=>{if(code)reject(new Error("Writer exited before the crash point"));});});
    const exited=new Promise((resolve)=>child.once("exit",resolve));child.kill("SIGKILL");await exited;
    assert.equal(f.service.report(f.binding).total_attempts,0);
    assert.equal(f.service.learningContext(f.binding).state.recent_attempts.length,0);
    answer(f.service,f.binding,v);assert.equal(f.service.report(f.binding).total_attempts,1);
  }finally{child.kill();f.service.close();}
});

test("another goal for the same learner has a separate history and ownership",()=>{const f=fixture();try{const learner=f.service.store.context(f.binding).learner_id;const b=f.service.initialize({name:"同一人新目标",learner_id:learner,exam_type:"国考",idempotency_key:"goal-2"}).binding_id;const v=f.service.start(f.binding,{count:1,idempotency_key:"s"});answer(f.service,f.binding,v);assert.equal(f.service.report(b).total_attempts,0);assert.throws(()=>f.service.resume(b,{session_id:v.session_id,idempotency_key:"cross-goal"}),{code:"OWNER_MISMATCH"});}finally{f.service.close();}});
test("AI suggestions stay separate until the learner confirms the error",()=>{const f=fixture();try{let v=f.service.start(f.binding,{count:2,idempotency_key:"s"});const feedback=answer(f.service,f.binding,v,"B").payload.feedback;let r=f.service.annotate(f.binding,{attempt_id:feedback.attempt_id,error_code:"K",confidence:0.3,idempotency_key:"suggest"});assert.equal(r.attempt.error_code,null);assert.equal(r.attempt.error_suggestion.confidence,0.3);assert.deepEqual(f.service.report(f.binding).modules[0].error_counts_30,{});f.service.annotate(f.binding,{attempt_id:feedback.attempt_id,error_code:"M",error_source:"user_confirmed",reasoning:"确认方法问题",idempotency_key:"confirm"});assert.equal(f.service.report(f.binding).modules[0].error_counts_30.M,1);assert.equal(f.service.report(f.binding).total_attempts,1);assert.equal(f.service.learningContext(f.binding).recent_full_attempts[0].reasoning,"确认方法问题");v=next(f.service,f.binding,v);answer(f.service,f.binding,v);assert.equal(f.service.report(f.binding).total_attempts,2);assert.equal(f.service.learningContext(f.binding).state.ability_profile.subtypes["资料分析::增长率"].error_counts_30.M,1);}finally{f.service.close();}});
test("ordinary elapsed time excludes downtime after a persisted heartbeat",()=>{let clock=new Date("2026-10-01T00:00:00Z");const f=fixture({now:()=>clock});let v=f.service.start(f.binding,{count:1,idempotency_key:"s"});clock=new Date(clock.getTime()+10000);f.service.draft(f.binding,{session_id:v.session_id,slot:0,note:"重启前思路",idempotency_key:"heartbeat"});f.service.close();clock=new Date(clock.getTime()+8*3600000);const restored=new LearningService({root:join(f.dir,"data"),bankPath:f.bankPath,now:()=>clock});try{v=restored.resume(f.binding,{session_id:v.session_id,idempotency_key:"resume"});clock=new Date(clock.getTime()+5000);const a=answer(restored,f.binding,v).payload.feedback;assert.equal(a.elapsed_seconds,15);assert.equal(a.reasoning,"重启前思路");}finally{restored.close();}});
test("legacy import and backup restore retries do not create fake attempts or duplicate profiles",()=>{const f=fixture();try{const input={state:{schema_version:"0.7",project_state_id:"ps_old",goal:{exam_targets:["省考"]},ability_profile:{old_count:99},review_queue:[],study_route:{steps:[{module:"资料分析",subtype:"增长率",completed_sessions:99}]}},idempotency_key:"legacy"};const a=f.service.importLegacy(input);assert.deepEqual(f.service.importLegacy(input),a);assert.equal(f.service.report(a.binding_id).total_attempts,0);assert.equal(f.service.learningContext(a.binding_id).state.study_route.steps[0].completed_sessions,0);const backup=f.service.exportBackup(a.learner_id);const restored=f.service.importBackup(backup,"restore");assert.deepEqual(f.service.importBackup(backup,"restore"),restored);assert.equal(f.service.store.list().length,3);const c=f.service.learningContext(a.binding_id);f.service.configure(a.binding_id,{steps:[{module:"资料分析",subtype:"增长率",completed_sessions:999,status:"done"}],idempotency_key:"route"});assert.equal(f.service.learningContext(a.binding_id).state.study_route.steps[0].completed_sessions,0);assert.equal(c.state.legacy_snapshot.ability_profile.old_count,99);}finally{f.service.close();}});

test("separate learners and targets never receive each other's records",()=>{const f=fixture();try{const b=f.service.initialize({name:"另一个人",idempotency_key:"init-b"}).binding_id;let v=f.service.start(f.binding,{count:3,session_mode:"quick",idempotency_key:"start"});const session=v.session_id;for(let i=0;i<3;i++){v=answer(f.service,f.binding,v);v=next(f.service,f.binding,v);}assert.equal(f.service.report(f.binding).total_attempts,3);assert.equal(f.service.report(b).total_attempts,0);assert.throws(()=>f.service.resume(b,{session_id:session,idempotency_key:"cross"}),{code:"OWNER_MISMATCH"});const attempt=f.service.learningContext(f.binding).recent_full_attempts[0];assert.throws(()=>f.service.annotate(b,{attempt_id:attempt.attempt_id,error_code:"K",error_source:"user_confirmed",idempotency_key:"cross-attempt"}),{code:"OWNER_MISMATCH"});assert.equal(f.service.report(b).total_attempts,0);}finally{f.service.close();}});
test("restart restores exact session, draft and full history",()=>{const f=fixture();let v=f.service.start(f.binding,{count:3,session_mode:"quick",idempotency_key:"s"});v=answer(f.service,f.binding,v);v=next(f.service,f.binding,v);v=answer(f.service,f.binding,v);v=next(f.service,f.binding,v);f.service.draft(f.binding,{session_id:v.session_id,slot:2,answer:"B",note:"我的思路",idempotency_key:"d"});f.service.pause(f.binding,{session_id:v.session_id,idempotency_key:"p"});f.service.close();const restored=new LearningService({root:join(f.dir,"data"),bankPath:f.bankPath});try{v=restored.resume(f.binding,{session_id:v.session_id,idempotency_key:"r"});assert.equal(v.payload.question.progress.current,3);assert.equal(v.payload.draft.answer,"B");assert.equal(v.payload.draft.note,"我的思路");assert.equal(restored.report(f.binding).total_attempts,2);answer(restored,f.binding,v);assert.equal(restored.report(f.binding).total_attempts,3);}finally{restored.close();}});
test("retry, start replay and pause/finish summaries cannot double count",()=>{const f=fixture();try{const input={count:3,session_mode:"quick",idempotency_key:"start"};let v=f.service.start(f.binding,input);assert.equal(f.service.start(f.binding,input).session_id,v.session_id);const a=answer(f.service,f.binding,v,"B","answer");assert.equal(answer(f.service,f.binding,v,"B","answer").payload.feedback.attempt_id,a.payload.feedback.attempt_id);assert.throws(()=>answer(f.service,f.binding,v,"A","answer"),{code:"REVISION_CONFLICT"});assert.throws(()=>answer(f.service,f.binding,v,"A","different"),{code:"REVISION_CONFLICT"});v=f.service.pause(f.binding,{session_id:v.session_id,idempotency_key:"pause"});v=f.service.resume(f.binding,{session_id:v.session_id,idempotency_key:"resume"});v=next(f.service,f.binding,v);for(let i=1;i<3;i++){v=answer(f.service,f.binding,v);v=next(f.service,f.binding,v);}assert.equal(f.service.report(f.binding).total_attempts,3);assert.equal(f.service.learningContext(f.binding).state.ability_profile.subtypes["资料分析::增长率"].sample_count,3);}finally{f.service.close();}});
test("failure midway through answer transaction leaves no partial learning state",()=>{const f=fixture();try{const v=f.service.start(f.binding,{count:3,session_mode:"quick",idempotency_key:"s"});const save=f.service.store.putState;f.service.store.putState=()=>{throw new Error("simulated disk failure");};assert.throws(()=>answer(f.service,f.binding,v),/simulated/);f.service.store.putState=save;assert.equal(f.service.report(f.binding).total_attempts,0);assert.equal(f.service.learningContext(f.binding).state.recent_attempts.length,0);assert.equal(f.service.store.getSession(f.service.store.context(f.binding),v.session_id).attempts.length,0);answer(f.service,f.binding,v);assert.equal(f.service.report(f.binding).total_attempts,1);}finally{f.service.close();}});
test("explicit sibling review advances only its linked task once",()=>{let clock=new Date("2026-10-01T00:00:00Z");const f=fixture({now:()=>clock});try{let v=f.service.start(f.binding,{count:1,session_mode:"quick",idempotency_key:"s"});const anchor=v.payload.question.question_id;answer(f.service,f.binding,v,"B");const task=f.service.learningContext(f.binding).state.review_queue[0];clock=new Date("2026-10-02T00:00:01Z");v=f.service.start(f.binding,{count:1,session_mode:"review",ignore_unfinished:true,idempotency_key:"review"});assert.notEqual(v.payload.question.question_id,anchor);answer(f.service,f.binding,v,"A","linked");answer(f.service,f.binding,v,"A","linked");const queue=f.service.learningContext(f.binding).state.review_queue;assert.equal(queue.find((q)=>q.review_task_id===task.review_task_id).stage,1);assert.equal(queue[0].anchor_question_id,anchor);}finally{f.service.close();}});
test("foundation exactly 15 questions and 9 correct advances route only once",()=>{const f=fixture();try{let v=f.service.start(f.binding,{session_mode:"chapter",purpose:"foundation",focus_module:"资料分析",focus_subtype:"增长率",idempotency_key:"f"});assert.equal(v.payload.question.progress.total,15);for(let i=0;i<15;i++){v=answer(f.service,f.binding,v,i<9?"A":"B");if(i<14&&(i+1)%3===0){v=f.service.pause(f.binding,{session_id:v.session_id,idempotency_key:"p"+i});v=f.service.resume(f.binding,{session_id:v.session_id,idempotency_key:"r"+i});}v=next(f.service,f.binding,v);}assert.equal(v.payload.foundation_passed,true);assert.equal(Object.keys(f.service.learningContext(f.binding).state.foundation_passes).length,1);assert.equal(f.service.learningContext(f.binding).state.study_route.steps[0].completed_sessions,1);}finally{f.service.close();}});
test("ordinary chapter never marks a foundation pass and inventory is honest",()=>{const f=fixture();try{let v=f.service.start(f.binding,{session_mode:"chapter",count:10,idempotency_key:"chapter"});for(let i=0;i<10;i++){v=answer(f.service,f.binding,v);v=next(f.service,f.binding,v);}assert.equal(Object.keys(f.service.report(f.binding).foundation_passes).length,0);assert.throws(()=>f.service.start(f.binding,{focus_module:"政治理论",count:3,ignore_unfinished:true,idempotency_key:"missing"}),{code:"BANK_INSUFFICIENT"});assert.equal(f.service.report(f.binding).total_attempts,10);}finally{f.service.close();}});
test("strict paper hides correctness until final submit and expiry survives a service restart",()=>{let clock=new Date("2026-10-01T00:00:00Z");const f=fixture({now:()=>clock});let service=f.service;try{let v=service.start(f.binding,{session_mode:"paper",timing_mode:"strict",available_minutes:1,idempotency_key:"strict"});assert.equal(JSON.stringify(v).includes("correct_answer"),false);v=service.draft(f.binding,{session_id:v.session_id,slot:0,answer:"A",idempotency_key:"draft"});assert.equal(service.report(f.binding).total_attempts,0);assert.throws(()=>service.pause(f.binding,{session_id:v.session_id,idempotency_key:"pause"}),{code:"INVALID_INPUT"});const deadline=v.payload.deadline;service.close();clock=new Date("2026-10-01T00:01:01Z");service=new LearningService({root:join(f.dir,"data"),bankPath:f.bankPath,now:()=>clock});assert.equal(service.store.getSession(service.store.context(f.binding),v.session_id).deadline,deadline);v=service.resume(f.binding,{session_id:v.session_id,idempotency_key:"expired"});assert.equal(v.payload.status,"EXPIRED");assert.equal(v.payload.correct,1);assert.equal(service.report(f.binding).total_attempts,20);service.submitPaper(f.binding,{session_id:v.session_id,idempotency_key:"again"});assert.equal(service.report(f.binding).total_attempts,20);}finally{service.close();}});
test("backup round trip on another machine retains media and rejects corruption",()=>{const f=fixture();const dir=root();const target=new LearningService({root:join(dir,"data")});try{const assetId="a".repeat(64);const assets=join(f.dir,"assets");mkdirSync(assets);writeFileSync(join(assets,assetId),Buffer.from("89504e470d0a1a0a","hex"));f.service.assetDir=assets;const q=question(0,{stem:`![题图](/bank-assets/${assetId})`});let v=f.service.start(f.binding,{questions:[q,question(1)],idempotency_key:"q"});v=answer(f.service,f.binding,v);v=next(f.service,f.binding,v);const backup=f.service.exportBackup(f.service.store.context(f.binding).learner_id);const restored=target.importBackup(backup);const b=target.store.bind(restored.learner_id,restored.goals[0]).binding_id;assert.equal(target.report(b).total_attempts,1);assert.equal(target.learningContext(b).unfinished_sessions[0].session_id,v.session_id);assert.deepEqual(readFileSync(join(dir,"data","profiles",restored.learner_id,"attachments",assetId)),Buffer.from("89504e470d0a1a0a","hex"));const count=target.store.list().length;backup.name="modified";assert.throws(()=>target.importBackup(backup),{code:"BACKUP_INVALID"});assert.equal(target.store.list().length,count);}finally{f.service.close();target.close();}});
test("loopback API requires credentials, rejects cross-origin and shares browser/MCP records",async()=>{const dir=root();const local=await createLocalServer({root:dir,bankPath:null,now:()=>new Date("2026-10-01T04:00:00Z")});try{let res=await fetch(`${local.origin}/rpc`,{method:"POST",body:"{}"});assert.equal(res.status,401);res=await fetch(`${local.origin}/rpc`,{method:"POST",headers:{Origin:"https://example.com",Authorization:`Bearer ${local.token}`},body:"{}"});assert.equal(res.status,403);const rpc=async(method,args)=>{const r=await fetch(`${local.origin}/rpc`,{method:"POST",headers:{Authorization:`Bearer ${local.token}`,"Content-Type":"application/json"},body:JSON.stringify({method,arguments:args})});const response=await r.json();assert.equal(r.status,200,JSON.stringify(response));return response.result;};const b=(await rpc("initialize_project_learning_state",{name:"API 学习者",idempotency_key:"i"})).binding_id;const v=await rpc("start_quiz_session",{binding_id:b,questions:[question(0)],idempotency_key:"s"});await rpc("submit_quiz_answer",{binding_id:b,session_id:v.session_id,session_item_id:v.payload.session_item_id,question_id:v.payload.question.question_id,answer:"A",idempotency_key:"a"});assert.equal((await rpc("get_progress_report",{binding_id:b})).total_attempts,1);}finally{await local.close();}});
test("50,000 full attempts are retained and report queries stay below one second",()=>{const f=fixture();try{const c=f.service.store.context(f.binding);const session={session_id:"load",goal_id:c.goal_id,status:"COMPLETED",updated_at:new Date().toISOString(),questions:[],attempts:[]};f.service.store.putSession(c.db,session);const insert=c.db.prepare("INSERT INTO attempts VALUES(?,?,?,?,?,?,?,?)");transaction(c.db,()=>{for(let i=0;i<50000;i++){const a={attempt_id:`load_${i}`,module:"资料分析",subtype:"增长率",correct:i%2===0,elapsed_seconds:20,attempted_at:new Date().toISOString()};insert.run(a.attempt_id,c.goal_id,"load",i,`q${i}`,a.attempted_at,Number(a.correct),JSON.stringify(a));}});const durations=[];for(let i=0;i<5;i++){const start=performance.now();assert.equal(f.service.report(f.binding).total_attempts,50000);durations.push(performance.now()-start);}assert.ok(Math.max(...durations)<1000,`report durations ${durations}`);console.log(`50k report ms: ${durations.map((d)=>Math.round(d)).join(", ")}`);}finally{f.service.close();}});
test("real stdio MCP clients share one daemon while learner data stays separate",async()=>{const dir=root();const env={...process.env,GONGKAO_DATA_DIR:dir};const entry=fileURLToPath(new URL("../mcp-stdio.js",import.meta.url));const clients=[];try{for(let i=0;i<2;i++){const client=new Client({name:`integration-${i}`,version:"1.0"});await client.connect(new StdioClientTransport({command:process.execPath,args:[entry],env,stderr:"pipe"}));clients.push(client);}const tools=(await clients[0].listTools()).tools;assert.ok(tools.some((t)=>t.name==="resume_quiz_session"));const call=async(client,name,args)=>{const r=await client.callTool({name,arguments:args});assert.ok(!r.isError,r.content?.[0]?.text);return r.structuredContent;};const a=await call(clients[0],"initialize_project_learning_state",{name:"MCP A",idempotency_key:"initA"});const b=await call(clients[1],"initialize_project_learning_state",{name:"MCP B",idempotency_key:"initB"});const v=await call(clients[0],"start_quiz_session",{binding_id:a.binding_id,questions:[question(0)],idempotency_key:"s"});const raced=await Promise.all(clients.map((client,i)=>client.callTool({name:"submit_quiz_answer",arguments:{binding_id:a.binding_id,session_id:v.session_id,session_item_id:v.payload.session_item_id,question_id:v.payload.question.question_id,answer:i?"B":"A",idempotency_key:"race"+i}})));assert.equal(raced.filter(r=>r.isError).length,1);assert.equal(raced.filter(r=>!r.isError).length,1);assert.equal((await call(clients[1],"get_progress_report",{binding_id:b.binding_id})).total_attempts,0);assert.equal((await call(clients[1],"get_progress_report",{binding_id:a.binding_id})).total_attempts,1);}finally{for(const client of clients)await client.close();try{const info=JSON.parse(readFileSync(join(dir,"runtime","service.json"),"utf8"));await fetch(`${info.origin}/shutdown`,{method:"POST",headers:{Authorization:`Bearer ${info.token}`}});}catch{}}});
